
CREATE DATABASE BLOOD_DONATION_MANAGEMENT_SYSTEM
USE BLOOD_DONATION_MANAGEMENT_SYSTEM

--CREATING TABLES
CREATE TABLE DONOR(
DONORID CHAR(7) PRIMARY KEY,
FNAME VARCHAR(30) NOT NULL,
LNAME VARCHAR(30) NOT NULL,
GENDER CHAR(1) NOT NULL,
DOB DATE NOT NULL,
AGE varchar(3) NOT NULL, 
BLOODGROUP CHAR(3) NOT NULL
)

CREATE TABLE DONORPHONE(
DONORID CHAR(7) NOT NULL FOREIGN KEY REFERENCES DONOR(DONORID),
PHONENUMBER CHAR(15) NOT  NULL,
PRIMARY KEY(DONORID,PHONENUMBER))

CREATE TABLE DONORADDRESS(
DONORID CHAR(7) NOT NULL FOREIGN KEY REFERENCES DONOR(DONORID),
ADDRESS VARCHAR(100) NOT NULL,
PRIMARY KEY(DONORID, ADDRESS))


CREATE TABLE RECIPIENT(
RECIPIENTID CHAR(7) PRIMARY KEY,
FNAME VARCHAR(30) NOT NULL,
LNAME VARCHAR(30) NOT NULL,
GENDER CHAR(1) NOT NULL,
DOB DATE NOT NULL,
BLOODGROUP CHAR(3) NOT NULL
)
CREATE TABLE HOSPITAL(
HOSPITALID CHAR(5) PRIMARY KEY,
NAME CHAR(60) NOT NULL,
LOCATION VARCHAR(100) NOT NULL)

CREATE TABLE BLOODBANK(
BLOODBANKID CHAR(3) PRIMARY KEY,
NAME CHAR(60) NOT NULL,
LOCATION VARCHAR(100) NOT NULL
 )

CREATE TABLE STAFF(
STAFFID CHAR(3) PRIMARY KEY,
FNAME VARCHAR(30) NOT NULL,
LNAME VARCHAR(30) NOT NULL,
POSITION VARCHAR(30) NOT NULL,
GENDER CHAR(1) NOT NULL,
DOB DATE NOT NULL,
ROLE CHAR(50) NOT NULL,
SALARY MONEY NOT NULL,
BLOODBANKID CHAR(3) FOREIGN KEY REFERENCES BLOODBANK(BLOODBANKID))


ALTER TABLE BLOODBANK ADD MANGSTAFFID CHAR(3) 
ALTER TABLE BLOODBANK ADD CONSTRAINT FK1 FOREIGN KEY(MANGSTAFFID) REFERENCES STAFF(STAFFID)


CREATE TABLE DONATION(
DONORID CHAR(7) NOT NULL FOREIGN KEY REFERENCES DONOR(DONORID),
BLOODBANKID CHAR(3) NOT NULL FOREIGN KEY REFERENCES BLOODBANK(BLOODBANKID),
STAFFID CHAR(3) NOT NULL FOREIGN KEY REFERENCES STAFF(STAFFID),
DATE DATE NOT NULL,
AMOUNTDONATED FLOAT NOT NULL,
PRIMARY KEY(DONORID,BLOODBANKID,STAFFID,DATE,AMOUNTDONATED)
)


CREATE TABLE BLOODBANKPHONE(
BLOODBANKID CHAR(3) NOT NULL FOREIGN KEY REFERENCES BLOODBANK(BLOODBANKID),
PHONENUMBER CHAR(15) NOT NULL,
PRIMARY KEY(BLOODBANKID,PHONENUMBER))
CREATE TABLE BLOODUNTITY(
BLOODBANKID CHAR(3) NOT NULL FOREIGN KEY REFERENCES BLOODBANK(BLOODBANKID),
BLOODGROUP CHAR(3) NOT NULL,
BLOADAMOUNT FLOAT NOT NULL,
DATE DATE NOT NULL,
PRIMARY KEY(BLOODBANKID,BLOADAMOUNT,DATE))


CREATE TABLE TRANSFUSION (
DONORID CHAR(7) NOT NULL FOREIGN KEY REFERENCES DONOR(DONORID),
BLOODBANKID CHAR(3) NOT NULL FOREIGN KEY REFERENCES BLOODBANK(BLOODBANKID),
RECIPIENTID CHAR(7) NOT NULL FOREIGN KEY REFERENCES RECIPIENT(RECIPIENTID),
HOSPITALID CHAR(5) NOT NULL FOREIGN KEY REFERENCES HOSPITAL(HOSPITALID),
DATE DATE NOT NULL,
TIME TIME NOT NULL,
AMOUNTTRANSFERRED FLOAT NOT NULL,
PRIMARY KEY(DONORID,BLOODBANKID,RECIPIENTID,HOSPITALID,DATE,TIME))


CREATE TABLE RECIPIENTPHONE(
RECIPIENTID CHAR(7) NOT NULL FOREIGN KEY REFERENCES RECIPIENT(RECIPIENTID),
PHONENUMBER CHAR(15) NOT  NULL,
PRIMARY KEY(RECIPIENTID,PHONENUMBER))


CREATE TABLE RECIPIENTADDRESS(
RECIPIENTID CHAR(7) NOT NULL FOREIGN KEY REFERENCES RECIPIENT(RECIPIENTID),
ADDRESS VARCHAR(100) NOT NULL,
PRIMARY KEY(RECIPIENTID, ADDRESS))

CREATE TABLE RECIPIENTMEDICALCONDITION(
RECIPIENTID CHAR(7) NOT NULL FOREIGN KEY REFERENCES RECIPIENT(RECIPIENTID),
 MEDICALHISTORY VARCHAR(50) NOT NULL,
PRIMARY KEY(RECIPIENTID,MEDICALHISTORY))


CREATE TABLE HOSPITALTELEPHONE(
HOSPITALID CHAR(5) NOT NULL FOREIGN KEY REFERENCES HOSPITAL(HOSPITALID),
PHONENUMBER CHAR(13) NOT  NULL,
PRIMARY KEY(HOSPITALID,PHONENUMBER))


CREATE TABLE STAFFPHONE(
STAFFID CHAR(3) NOT NULL FOREIGN KEY REFERENCES STAFF(STAFFID),
PHONENUMBER CHAR(13) NOT  NULL,
PRIMARY KEY(STAFFID,PHONENUMBER))


CREATE TABLE STAFFADDRESS(
STAFFID CHAR(3) NOT NULL FOREIGN KEY REFERENCES STAFF(STAFFID),
ADDRESS VARCHAR(100) NOT NULL,
PRIMARY KEY(STAFFID, ADDRESS))


--INSERT STATEMENTS


INSERT INTO DONOR 
VALUES('D000001','Dawit','Girma','M','2002-10-25','54','O+')

INSERT INTO BLOODBANK(BLOODBANKID,NAME,LOCATION)
VALUES('B01','BLOODBANK1','Addis Ababa')

INSERT INTO STAFF
VALUES('S01','Adoniyas','Bekele','Assistant','M','2002-08-20','BLOOD BANK MEDICAL LAB ASSISTANT','20,000','B01')

UPDATE BLOODBANKPHONE
SET PHONENUMBER='0944375911' WHERE BLOODBANKID='B01'

INSERT INTO BLOODBANK
VALUES('B01','+251119080808')

INSERT INTO BLOODUNTITY   
VALUES ('B01','O+',1000.00,'2023-03-01')

INSERT INTO DONATION
VALUES('D000001','B01','S01','2023-03-01',500.00)


INSERT INTO DONORADDRESS
VALUES('D000001','Addis Ababa')


INSERT INTO DONORPHONE
VALUES('D000001','+251970707070')


INSERT INTO HOSPITAL
VALUES('H0001','TIKUR ANBESA HOSPITAL','Addis Ababa')


INSERT INTO HOSPITALTELEPHONE
VALUES('H0001','+25131401281')


INSERT INTO RECIPIENT   
VALUES('R000001','Fasika', 'Ewnetu', 'F', '2001-08-12','AB+')
select * from recipient
 
INSERT INTO RECIPIENTADDRESS    
VALUES('R000001','Kolfe Keraniyo')


INSERT INTO RECIPIENTMEDICALCONDITION
VALUES('R000001','Hemophilia')   

INSERT INTO RECIPIENTPHONE   
VALUES('R000001','+2519080899')

INSERT INTO STAFFADDRESS
VALUES('S01','Kirkos')

INSERT INTO STAFFPHONE
VALUES('S01','+251901010101')


INSERT INTO TRANSFUSION         
VALUES('D000001','B01','R000001','H0001','2023-03-01','02:20',500)

UPDATE DONOR 
SET FNAME='Temesgen', LNAME=' Gonfa', GENDER='M', DOB='2001-02-27', BLOODGROUP='AB-'
WHERE DONORID='D000001'

--VIEW AND PRIVILEGE STATEMENTS
CREATE VIEW DONOR_INFORMATION AS
 SELECT DONOR.DONORID,FNAME,LNAME,BLOODGROUP,DOB,PHONENUMBER 
 FROM DONOR INNER JOIN DONORPHONE
 ON DONOR.DONORID=DONORPHONE.DONORID


SELECT *FROM DONOR_INFORMATION

CREATE VIEW RECIPIENT_INFORMATION AS
SELECT RECIPIENT.RECIPIENTID,FNAME,LNAME,BLOODGROUP,DOB
 FROM RECIPIENT INNER JOIN RECIPIENTMEDICALCONDITION
 ON RECIPIENT.RECIPIENTID=RECIPIENTMEDICALCONDITION.RECIPIENTID


 SELECT*FROM RECIPIENT_INFORMATION

 CREATE VIEW HOSPITAL_INFORMATION AS
 SELECT HOSPITAL.HOSPITALID,NAME,LOCATION,PHONENUMBER
 FROM HOSPITAL INNER JOIN HOSPITALTELEPHONE
 ON HOSPITAL.HOSPITALID=HOSPITALTELEPHONE.HOSPITALID

  SELECT*FROM HOSPITAL_INFORMATION

  CREATE VIEW  STAFF_INFORMATION AS
  SELECT STAFF.STAFFID,FNAME,LNAME,ROLE,DOB,BLOODBANKID,SALARY,PHONENUMBER 
 FROM STAFF INNER JOIN STAFFPHONE
 ON STAFF.STAFFID=STAFFPHONE.STAFFID


 SELECT*FROM STAFF_INFORMATION

 CREATE VIEW MANG_PRIVILEGE AS
 SELECT DONOR_INFORMATION.DONORID,FNAME,LNAME,BLOODGROUP,DOB,PHONENUMBER,ADDRESS 
 FROM DONOR_INFORMATION INNER JOIN DONORADDRESS
 ON DONOR_INFORMATION.DONORID=DONORADDRESS.DONORID

 SELECT * FROM MANG_PRIVILEGE

 --MANAGER'S PRIVILEGE ON UPDATE
 UPDATE STAFF 
 SET SALARY='10,000' 
 WHERE STAFFID='S01'

  CREATE VIEW MANG_PRIVILEGE2 AS
  SELECT STAFF_INFORMATION.STAFFID,FNAME,LNAME,ROLE,DOB,BLOODBANKID,SALARY,PHONENUMBER,ADDRESS 
 FROM STAFF_INFORMATION INNER JOIN STAFFADDRESS
 ON STAFF_INFORMATION.STAFFID=STAFFADDRESS.STAFFID


 SELECT *FROM MANG_PRIVILEGE2

